### ISSUE TITLE
An error is reported when executing python3 example1.py

### ISSUE THREAD

**Issue by shuimoshusheng** [RiccardoFedrizzi/comnetsemu_5Gnet#2]
Traceback (most recent call last):
  File "example1.py", line 6, in <module>
    from comnetsemu.cli import CLI, spawnXtermDocker
ModuleNotFoundError: No module named 'comnetsemu'

**Comment by RiccardoFedrizzi** [comment]
Hi, this seems a python import error... pls ensure you correctly installed the comnetsemu environment and check the example dockerindocker.py is correctly working.

**Comment by shuimoshusheng** [comment]
> Hi, this seems a python import error... pls ensure you correctly installed the comnetsemu environment and check the example dockerindocker.py is correctly working.

It should be that my environment is not installed properly, thank you very much
